// WebFalcor: C wrapper over the NRD library for the wasm build (NRDPass's use of the nrd:: API).
// Settings structs are written in place by JS, which learns their layout from nrdw_fields().
// Descriptions and dispatches come back as JSON; constant data stays in wasm memory.
#include "NRD.h"
#include <cstddef>
#include <cstdio>
#include <cstdarg>
#include <cstdlib>
#include <cstring>
#include <string>
#include <emscripten/emscripten.h>

#include "fields.inc" // generated by scripts/build-nrd-wasm.mjs from NRDSettings.h

namespace
{
nrd::Denoiser* gDenoiser = nullptr;
nrd::Method gMethod = nrd::Method::RELAX_DIFFUSE_SPECULAR;
nrd::CommonSettings gCommon;
nrd::RelaxDiffuseSpecularSettings gRelaxDiffuseSpecular;
nrd::RelaxDiffuseSettings gRelaxDiffuse;
nrd::ReblurSettings gReblur;
nrd::SpecularReflectionMvSettings gSpecularReflectionMv;
nrd::SpecularDeltaMvSettings gSpecularDeltaMv;
std::string gJson;

void* allocate(void*, size_t size, size_t alignment) { return aligned_alloc(alignment < sizeof(void*) ? sizeof(void*) : alignment, (size + alignment - 1) / alignment * alignment); }
void* reallocate(void*, void* memory, size_t size, size_t alignment)
{
    void* p = realloc(memory, size);
    (void)alignment;
    return p;
}
void release(void*, void* memory) { free(memory); }

void appendf(const char* fmt, ...) __attribute__((format(printf, 1, 2)));
void appendf(const char* fmt, ...)
{
    char buf[512];
    va_list args;
    va_start(args, fmt);
    vsnprintf(buf, sizeof(buf), fmt, args);
    va_end(args);
    gJson += buf;
}
} // namespace

extern "C"
{

/** Field tables of the settings structs: {"CommonSettings":{"size":N,"fields":[[name,offset,type,count],...]},...}. */
EMSCRIPTEN_KEEPALIVE const char* nrdw_fields()
{
    gJson = "{";
#define F(S, name, type, count) appendf("[\"" #name "\",%zu,\"" type "\",%d],", offsetof(nrd::S, name), count);
#define STRUCT(S)                                         \
    appendf("\"" #S "\":{\"size\":%zu,\"fields\":[", sizeof(nrd::S)); \
    FIELDS_##S                                            \
    if (gJson.back() == ',') gJson.pop_back();            \
    gJson += "]},";
    STRUCT(CommonSettings)
    STRUCT(RelaxDiffuseSpecularSettings)
    STRUCT(RelaxDiffuseSettings)
    STRUCT(ReblurSettings)
    STRUCT(SpecularReflectionMvSettings)
    STRUCT(SpecularDeltaMvSettings)
#undef STRUCT
#undef F
    gJson.pop_back();
    gJson += "}";
    return gJson.c_str();
}

/** The default-initialized settings instances JS edits in place. */
EMSCRIPTEN_KEEPALIVE void* nrdw_settings(const char* name)
{
    if (!strcmp(name, "CommonSettings")) return &gCommon;
    if (!strcmp(name, "RelaxDiffuseSpecularSettings")) return &gRelaxDiffuseSpecular;
    if (!strcmp(name, "RelaxDiffuseSettings")) return &gRelaxDiffuse;
    if (!strcmp(name, "ReblurSettings")) return &gReblur;
    if (!strcmp(name, "SpecularReflectionMvSettings")) return &gSpecularReflectionMv;
    if (!strcmp(name, "SpecularDeltaMvSettings")) return &gSpecularDeltaMv;
    return nullptr;
}

EMSCRIPTEN_KEEPALIVE const char* nrdw_library()
{
    const nrd::LibraryDesc& d = nrd::GetLibraryDesc();
    gJson.clear();
    appendf("{\"version\":[%u,%u,%u],", d.versionMajor, d.versionMinor, d.versionBuild);
    appendf("\"spirvBindingOffsets\":[%u,%u,%u,%u]}", d.spirvBindingOffsets.samplerOffset, d.spirvBindingOffsets.textureOffset, d.spirvBindingOffsets.constantBufferOffset, d.spirvBindingOffsets.storageTextureAndBufferOffset);
    return gJson.c_str();
}

/** Mirrors NRDPass::reinit's CreateDenoiser; returns nrd::Result. */
EMSCRIPTEN_KEEPALIVE int nrdw_create(int method, int width, int height)
{
    if (gDenoiser) nrd::DestroyDenoiser(*gDenoiser);
    gDenoiser = nullptr;
    gMethod = nrd::Method(method);
    const nrd::MethodDesc methods[] = {{gMethod, uint16_t(width), uint16_t(height)}};
    nrd::DenoiserCreationDesc desc = {};
    desc.memoryAllocatorInterface.Allocate = allocate;
    desc.memoryAllocatorInterface.Reallocate = reallocate;
    desc.memoryAllocatorInterface.Free = release;
    desc.requestedMethodNum = 1;
    desc.requestedMethods = methods;
    return int(nrd::CreateDenoiser(desc, gDenoiser));
}

/** Mirrors nrd::SetMethodSettings with the instance for `method`. */
EMSCRIPTEN_KEEPALIVE int nrdw_set_method_settings(int method)
{
    const void* s = nullptr;
    switch (nrd::Method(method))
    {
    case nrd::Method::RELAX_DIFFUSE_SPECULAR: s = &gRelaxDiffuseSpecular; break;
    case nrd::Method::RELAX_DIFFUSE: s = &gRelaxDiffuse; break;
    case nrd::Method::REBLUR_DIFFUSE_SPECULAR: s = &gReblur; break;
    case nrd::Method::SPECULAR_REFLECTION_MV: s = &gSpecularReflectionMv; break;
    case nrd::Method::SPECULAR_DELTA_MV: s = &gSpecularDeltaMv; break;
    default: return -1;
    }
    return int(nrd::SetMethodSettings(*gDenoiser, nrd::Method(method), s));
}

/** Mirrors nrd::GetDenoiserDesc: pipelines, samplers, texture pools, constant buffer. */
EMSCRIPTEN_KEEPALIVE const char* nrdw_denoiser_desc()
{
    const nrd::DenoiserDesc& d = nrd::GetDenoiserDesc(*gDenoiser);
    gJson = "{\"pipelines\":[";
    for (uint32_t i = 0; i < d.pipelineNum; i++)
    {
        const nrd::PipelineDesc& p = d.pipelines[i];
        appendf("{\"shader\":\"%s\",\"entry\":\"%s\",\"hasConstantData\":%s,\"ranges\":[", p.shaderFileName ? p.shaderFileName : "", p.shaderEntryPointName ? p.shaderEntryPointName : "main", p.hasConstantData ? "true" : "false");
        for (uint32_t r = 0; r < p.descriptorRangeNum; r++)
            appendf("%s{\"type\":%u,\"base\":%u,\"count\":%u}", r ? "," : "", (unsigned)p.descriptorRanges[r].descriptorType, p.descriptorRanges[r].baseRegisterIndex, p.descriptorRanges[r].descriptorNum);
        appendf("]}%s", i + 1 < d.pipelineNum ? "," : "");
    }
    gJson += "],\"samplers\":[";
    for (uint32_t i = 0; i < d.staticSamplerNum; i++)
        appendf("%s{\"sampler\":%u,\"register\":%u}", i ? "," : "", (unsigned)d.staticSamplers[i].sampler, d.staticSamplers[i].registerIndex);
    auto pool = [](const char* name, const nrd::TextureDesc* t, uint32_t n) {
        appendf("],\"%s\":[", name);
        for (uint32_t i = 0; i < n; i++) appendf("%s{\"format\":%u,\"width\":%u,\"height\":%u,\"mipNum\":%u}", i ? "," : "", (unsigned)t[i].format, t[i].width, t[i].height, t[i].mipNum);
    };
    pool("permanentPool", d.permanentPool, d.permanentPoolSize);
    pool("transientPool", d.transientPool, d.transientPoolSize);
    appendf("],\"constantBuffer\":{\"maxDataSize\":%u,\"register\":%u},\"descriptorSet\":{\"setMaxNum\":%u,\"textureMaxNum\":%u,\"storageTextureMaxNum\":%u}}", d.constantBufferDesc.maxDataSize, d.constantBufferDesc.registerIndex, d.descriptorSetDesc.setMaxNum, d.descriptorSetDesc.textureMaxNum, d.descriptorSetDesc.storageTextureMaxNum);
    return gJson.c_str();
}

/** Mirrors nrd::GetComputeDispatches with gCommon; constant data as [pointer, size] into wasm memory. */
EMSCRIPTEN_KEEPALIVE const char* nrdw_dispatches()
{
    const nrd::DispatchDesc* descs = nullptr;
    uint32_t num = 0;
    nrd::Result res = nrd::GetComputeDispatches(*gDenoiser, gCommon, descs, num);
    gJson.clear();
    if (res != nrd::Result::SUCCESS)
    {
        appendf("{\"error\":%d}", int(res));
        return gJson.c_str();
    }
    gJson = "[";
    for (uint32_t i = 0; i < num; i++)
    {
        const nrd::DispatchDesc& dd = descs[i];
        appendf("%s{\"name\":\"%s\",\"pipeline\":%u,\"grid\":[%u,%u],\"constants\":[%lu,%u],\"resources\":[", i ? "," : "", dd.name ? dd.name : "", dd.pipelineIndex, dd.gridWidth, dd.gridHeight, (unsigned long)(uintptr_t)dd.constantBufferData, dd.constantBufferDataSize);
        for (uint32_t r = 0; r < dd.resourceNum; r++)
        {
            const nrd::Resource& res = dd.resources[r];
            appendf("%s[%u,%u,%u,%u,%u]", r ? "," : "", (unsigned)res.stateNeeded, (unsigned)res.type, res.indexInPool, res.mipOffset, res.mipNum);
        }
        gJson += "]}";
    }
    gJson += "]";
    return gJson.c_str();
}

EMSCRIPTEN_KEEPALIVE void nrdw_destroy()
{
    if (gDenoiser) nrd::DestroyDenoiser(*gDenoiser);
    gDenoiser = nullptr;
}
}
