/**
 * NDSDFGrid host pinned against the gcc/libstdc++ reference dump
 * (tests/oracle/assets/ndsdf-cheese-ref.json, generated by cheese-ref.cpp:
 * SDFGrid::generateCheeseValues(128, 0) + NDSDFGrid quantization with
 * narrowBandThickness 2.5 — the NDSDFGrid.pyscene configuration).
 */

import { describe, expect, it } from "vitest";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { NDSDFGrid } from "../src/Scene/SDFs/NDSDFGrid.js";

interface CheeseRef {
    holes: [number, number, number, number][];
    lodCount: number;
    coarsestWidth: number;
    coarsestNorm: number;
    cornerSamples: number[];
    quantSamples: [number, number, number, number, number][];
}

const ref = JSON.parse(
    readFileSync(resolve(__dirname, "../../../tests/oracle/assets/ndsdf-cheese-ref.json"), "utf8"),
) as CheeseRef;

describe("NDSDFGrid cheese generation (bit-exact vs gcc reference)", () => {
    const grid = new NDSDFGrid(2.5);
    grid.generateCheeseValues(128, 0);

    it("matches LOD configuration", () => {
        expect(grid.lodCount).toBe(ref.lodCount);
        expect(grid.coarsestLODGridWidth).toBe(ref.coarsestWidth);
        expect(grid.coarsestLODNormalizationFactor).toBeCloseTo(ref.coarsestNorm, 9);
        expect(grid.coarsestLODAsLevel).toBe(3);
    });

    it("matches quantized snorm8 values exactly at all probe points", () => {
        for (const [lod, x, y, z, q] of ref.quantSamples) {
            const lw = 1 + (grid.coarsestLODGridWidth << lod);
            const got = grid.values[lod]![x + lw * (y + lw * z)]!;
            expect(got, `lod ${lod} @ (${x},${y},${z})`).toBe(q);
        }
    });

    it("assembles the Z-stacked atlas with intact LOD slabs", () => {
        const atlas = grid.buildAtlas();
        expect(atlas.width).toBe(129);
        expect(atlas.depth).toBe(5 + 8 * 31);
        for (const [lod, x, y, z, q] of ref.quantSamples) {
            const zBase = lod + grid.coarsestLODGridWidth * ((1 << lod) - 1);
            expect(atlas.data[x + atlas.width * (y + atlas.width * (zBase + z))], `atlas lod ${lod}`).toBe(q);
        }
    });
});
