#!/usr/bin/env node
/**
 * Generates packages/falcor/src/Utils/Color/SpectraData.ts from the upstream
 * Falcor sources, so the web uses exactly native's spectral tables:
 *   - Source/Falcor/Utils/Color/Spectra.inl   (CIE curves and measured data, from pbrt-v4)
 *   - Source/Falcor/Utils/Color/Spectrum.cpp  (the name -> table map and each
 *     table's normalization flag)
 *
 * Usage: node scripts/gen-spectra.mjs [--falcor <path to Falcor clone>]
 */

import { readFileSync, writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const argIdx = process.argv.indexOf("--falcor");
const falcorRoot = argIdx >= 0 ? resolve(process.argv[argIdx + 1]) : resolve(repoRoot, "Falcor");
const colorDir = resolve(falcorRoot, "Source/Falcor/Utils/Color");

const inl = readFileSync(resolve(colorDir, "Spectra.inl"), "utf8").replace(/\/\/[^\n]*/g, "");
const cpp = readFileSync(resolve(colorDir, "Spectrum.cpp"), "utf8");

// Every `const float NAME[...] = { numbers };` table.
const tables = new Map();
for (const m of inl.matchAll(/const\s+float\s+(\w+)\s*\[[^\]]*\]\s*=\s*\{([^}]*)\}/g)) {
    const values = m[2].split(",").map((t) => t.trim()).filter((t) => t.length > 0);
    for (const v of values) if (!/^[-+]?(\d+\.?\d*|\.\d+)([eE][-+]?\d+)?f?$/.test(v)) throw new Error(`gen-spectra: unexpected token '${v}' in ${m[1]}`);
    tables.set(m[1], values.map((v) => v.replace(/f$/, "")));
}

// The kNamedSpectra entries: {"name", PiecewiseLinearSpectrum::fromInterleaved(TABLE, normalize)}.
const named = [];
for (const m of cpp.matchAll(/\{\s*"([^"]+)"\s*,\s*PiecewiseLinearSpectrum::fromInterleaved\(\s*(\w+)\s*,\s*(true|false)\s*\)\s*\}/g)) {
    if (!tables.has(m[2])) throw new Error(`gen-spectra: named spectrum '${m[1]}' uses unknown table ${m[2]}`);
    named.push({ name: m[1], table: m[2], normalize: m[3] === "true" });
}
if (named.length === 0) throw new Error("gen-spectra: no named spectra found in Spectrum.cpp");
for (const cie of ["CIE_X", "CIE_Y", "CIE_Z"]) if (!tables.has(cie)) throw new Error(`gen-spectra: missing ${cie}`);

const used = new Set(["CIE_X", "CIE_Y", "CIE_Z", ...named.map((n) => n.table)]);
const lines = [
    "// Generated by scripts/gen-spectra.mjs from Falcor's Utils/Color/Spectra.inl and",
    "// Spectrum.cpp (spectral data originally from pbrt-v4). Do not edit by hand.",
    "/* eslint-disable */",
    "",
];
for (const name of [...used].sort()) lines.push(`const ${name} = [${tables.get(name).join(",")}];`);
lines.push("");
lines.push("/** CIE 1931 colour matching functions, 360..830 nm in 1 nm steps (native kCIE_X/Y/Z). */");
lines.push("export const kCIE_X = new Float32Array(CIE_X);");
lines.push("export const kCIE_Y = new Float32Array(CIE_Y);");
lines.push("export const kCIE_Z = new Float32Array(CIE_Z);");
lines.push("");
lines.push("/** Native kNamedSpectra: interleaved (wavelength, value) pairs and whether to normalize to CIE Y. */");
lines.push("export const kNamedSpectrumTables: Record<string, { interleaved: Float32Array; normalize: boolean }> = {");
for (const n of named) lines.push(`    ${JSON.stringify(n.name)}: { interleaved: new Float32Array(${n.table}), normalize: ${n.normalize} },`);
lines.push("};");
lines.push("");

const out = resolve(repoRoot, "packages/falcor/src/Utils/Color/SpectraData.ts");
writeFileSync(out, lines.join("\n"));
console.log(`SpectraData.ts: ${named.length} named spectra over ${used.size} tables`);
